### PR TITLE
Upgrade to use new pinnacle gradebook

### PR DESCRIPTION
**Pull request by theKidOfArcrania**
Mainly I just wrote some more robust code, so that it won't as easily break. Doesn't include actual parsing at this point (@creativitRy has not started to do that part), but it does include a basic test case just to test out all the components (note that you still need to login with an account, though).

### CODE REVIEW

**Comment by sid-kap** [comment]
I briefly looked at the code, and the changes look good! I'm glad you are phasing out the janky HTTP functions, and that you migrated some data types from JSONObject to actual classes.

I'd be happy to merge it if you think it's in a good state. (In fact, I think I'll go ahead and give @theKidOfArcrania and @creativitRy push access). 

However, I have a small nit: Is it common practice to add the `.idea` directory into source control? If not, should we maybe gitignore it and add a commit that removes the directory?

**Comment by sid-kap** [comment]
By the way, I am thinking about making a Github organization called "yourpisd" and moving this repo to under there. Any objections? @hanli1

**Comment by theKidOfArcrania** [comment]
Okay the .idea folder has been removed

**Comment by hanli1** [comment]
https://www.gitignore.io/ 

Ah yes I highly recommend not pushing anything build related.

**Pull request merged**
