### PR TITLE
Kill unused methods in Request.java

### PR DESCRIPTION
**Pull request by sid-kap**
Glad that we moved away from these janky methods! Only one function left

### CODE REVIEW

**Comment by theKidOfArcrania** [comment]
Yup :) Very nice

**Comment by sid-kap** [comment]
Maybe something like [this](http://stackoverflow.com/a/12465591/2755648) could work? We wouldn't be able to remove the `Request.getBitmap` function, but we could make it much shorter.

**Comment by theKidOfArcrania** [comment]
Oh... that works too

**Comment by sid-kap** [comment]
I'm a bit confused by your change---do we want to remove support for HTTPS? If so, we might as well get rid of the `isSecure` parameter as well.

**Comment by sid-kap** [comment]
Also, the one usage of `getBitmap` (in `Student.java`) uses an HTTPS link, so maybe we should use `HttpsUrlConnection`, not `HttpUrlConnection`.

**Comment by theKidOfArcrania** [comment]
The reason why I did that is because we don't actually need to cast into HttpsURLConnection because HttpsUrlConnection extends from HttpUrlConnection

**Comment by sid-kap** [comment]
Ah, I didn't know that.

It looks like `isSecure` isn't used at all in the method. Can we just remove it?

**Comment by theKidOfArcrania** [comment]
Yes. Also I believe there are some unused imports. (I was in a hurry to commit that yesterday).

**Comment by sid-kap** [comment]
:+1:

**Pull request merged**
